<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputPath>..\..\..\Game\server\</OutputPath>
		<OutputType>Exe</OutputType>
		<RootNamespace>Server</RootNamespace>
		<AssemblyName>Server</AssemblyName>
	</PropertyGroup>

	<!-- Exe Specific -->
	<PropertyGroup>
		<StartupObject>Server.Core</StartupObject>
		<ApplicationIcon>Server.ico</ApplicationIcon>
		<NoWin32Manifest>true</NoWin32Manifest>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
	</PropertyGroup>
	
</Project>
